feat/STADTKLN-67-dataset-detail-page
virtualidentityag/stadtKoeln-openData-frontend pull request #6
Opened 2024-09-03 12:03 UTC by paulovareiro29

2024-09-04 13:20 UTC, koepferd requested changes

2024-09-04 13:20 UTC, koepferd commented on src/styles/components/_button.scss
> +// .btn-secondary {
Do you think we might need the secondary button styles again? I'd suggest deleting them instead of just commenting.

2024-09-04 13:20 UTC, koepferd commented on src/pages/dataset.twig
> +        <span class='ms-2'>Share</span>
```suggestion
        <span class='ms-2'>Teilen</span>
```

2024-09-04 13:20 UTC, koepferd commented on src/pages/dataset.twig
> +      <button class='btn btn-primary d-block d-lg-none' aria-label='Share'>
```suggestion
      <button class='btn btn-primary d-block d-lg-none' aria-label='Teilen'>
```

2024-09-04 13:22 UTC, paulovareiro29 commented on src/styles/components/_button.scss
> +// .btn-secondary {
Just removed it 😄

2024-09-05 08:54 UTC, koepferd approved these changes

2024-09-05 09:01 UTC, merged